// ── Hangout Area — Node.js backend ──────────────────────────────────────
//
// 1. Serves the static game files (swm_hangouts.html, textures/, etc.)
// 2. Runs a WebSocket server for real-time multiplayer: join/leave, position
//    sync, ephemeral chat, and a lightweight in-memory identity system.
//
// ── Identity model (important for security) ─────────────────────────────
// Two different IDs are in play, and they are NOT interchangeable:
//
//  - `connId`     — generated by the SERVER for each WebSocket connection.
//                   This is what gets broadcast to OTHER players, so they
//                   can tell "this movement belongs to rig X". Not secret.
//
//  - `identityUuid` — generated by the CLIENT (crypto.randomUUID() in the
//                   browser) and saved in that browser's localStorage. Sent
//                   to the server on join so it can look up your saved
//                   name/skin from a previous connection *this server run*.
//                   This value is NEVER broadcast to other players — only
//                   used server-side as a private lookup key. If it were
//                   shared with other clients, anyone could reuse it to
//                   hijack another player's saved name/skin.
//
// ── Persistence model ────────────────────────────────────────────────────
// In-memory only (a plain Map), by design: "every time server restarts,
// everything gets deleted" was an explicit requirement. As long as the
// server keeps running, a returning identityUuid gets its name/skin back;
// restart the process and it's gone. If you want this to survive restarts
// later, swap the Map for SQLite/a file — the rest of the protocol doesn't
// need to change.

const express = require('express');
const http = require('http');
const path = require('path');
const { WebSocketServer } = require('ws');
const { randomUUID } = require('crypto');

const PORT = process.env.PORT || 3000;
const STATIC_DIR = __dirname;

const app = express();
app.use(express.static(STATIC_DIR));

const server = http.createServer(app);
const wss = new WebSocketServer({ server, path: '/ws' });

// ── Persistent (per-server-uptime) player profiles ───────────────────────
// identityUuid -> { name, skin, lastSeen }
const profiles = new Map();

// ── Active connections ────────────────────────────────────────────────────
// connId -> { connId, identityUuid, ws, name, skin, x, y, z, yaw, viewMode,
//             lastMoveTime, lastChatTime }
const players = new Map();

// ── Validation / security helpers ─────────────────────────────────────────
const MAP_BOUND = 6000;       // generous clamp around the ±5000 playable area
const MAX_NAME_LEN = 20;
const MAX_CHAT_LEN = 200;
const MAX_SKIN_CHARS = 150000; // ~110KB decoded — plenty for a 64x64 PNG skin, not enough to DoS
const MOVE_MIN_INTERVAL_MS = 30;   // ~33 updates/sec ceiling per player
const CHAT_MIN_INTERVAL_MS = 400;  // basic spam guard

function isValidIdentityUuid(v) {
    return typeof v === 'string' && /^[0-9a-f-]{10,64}$/i.test(v);
}
function sanitizeName(name) {
    if (typeof name !== 'string') return 'Player';
    const cleaned = name.replace(/[\x00-\x1F\x7F]/g, '').trim(); // strip control chars
    return cleaned.slice(0, MAX_NAME_LEN) || 'Player';
}
function sanitizeSkin(skin) {
    if (typeof skin !== 'string') return null;
    if (!skin.startsWith('data:image/png;base64,')) return null;
    if (skin.length > MAX_SKIN_CHARS) return null; // reject oversized payloads outright
    return skin;
}
function sanitizeChatText(text) {
    if (typeof text !== 'string') return null;
    const cleaned = text.replace(/[\x00-\x1F\x7F]/g, '').trim();
    if (!cleaned) return null;
    return cleaned.slice(0, MAX_CHAT_LEN);
}
function clampCoord(v, fallback) {
    const n = Number(v);
    if (!Number.isFinite(n)) return fallback;
    return Math.max(-MAP_BOUND, Math.min(MAP_BOUND, n));
}

function broadcast(message, exceptConnId) {
    const data = JSON.stringify(message);
    for (const player of players.values()) {
        if (player.connId === exceptConnId) continue;
        if (player.ws.readyState === player.ws.OPEN) {
            player.ws.send(data);
        }
    }
}

function publicPlayerData(player) {
    // What other clients are allowed to know — connId, not identityUuid.
    return {
        connId: player.connId,
        name: player.name,
        skin: player.skin,
        x: player.x, y: player.y, z: player.z,
        yaw: player.yaw,
        viewMode: player.viewMode,
        sprint: !!player.sprint,
    };
}

function isIdentityActive(identityUuid) {
    for (const p of players.values()) {
        if (p.identityUuid === identityUuid) return true;
    }
    return false;
}

wss.on('connection', ws => {
    const connId = randomUUID();
    let joined = false;

    // Heartbeat: browsers/OSes don't always send a clean close frame when a
    // connection actually dies (crashed tab, network drop, laptop sleep).
    // Without this, a dead player can sit as a "ghost" in the world forever
    // — the periodic sweep below terminates anyone who stops responding.
    ws.isAlive = true;
    ws.on('pong', () => { ws.isAlive = true; });

    ws.on('message', raw => {
        let msg;
        try {
            msg = JSON.parse(raw);
        } catch (e) {
            return; // ignore malformed JSON rather than crashing the connection
        }
        if (!msg || typeof msg.type !== 'string') return;

        const player = players.get(connId);

        switch (msg.type) {
            case 'join': {
                if (joined) return; // one join per connection

                let identityUuid = isValidIdentityUuid(msg.identityUuid) ? msg.identityUuid : randomUUID();

                // Refuse to let a second connection hijack an identity that's
                // already actively connected elsewhere right now.
                if (isIdentityActive(identityUuid)) {
                    ws.send(JSON.stringify({ type: 'error', message: 'This identity is already connected elsewhere.' }));
                    ws.close();
                    return;
                }

                const existing = profiles.get(identityUuid);
                const name = sanitizeName(msg.name ?? existing?.name);
                const skin = sanitizeSkin(msg.skin) || existing?.skin || null;

                profiles.set(identityUuid, { name, skin, lastSeen: Date.now() });

                const newPlayer = {
                    connId, identityUuid, ws,
                    name, skin,
                    x: clampCoord(msg.x, 0), y: clampCoord(msg.y, 5), z: clampCoord(msg.z, 0),
                    yaw: Number.isFinite(Number(msg.yaw)) ? Number(msg.yaw) : 0,
                    viewMode: 'first', sprint: false,
                    lastMoveTime: 0, lastChatTime: 0,
                };
                players.set(connId, newPlayer);
                joined = true;

                ws.send(JSON.stringify({
                    type: 'welcome',
                    connId,
                    identityUuid, // sent back so the client can save it if it just generated one
                    players: [...players.values()]
                        .filter(p => p.connId !== connId)
                        .map(publicPlayerData),
                }));
                broadcast({ type: 'playerJoined', player: publicPlayerData(newPlayer) }, connId);
                break;
            }

            case 'move': {
                if (!joined || !player) return;
                const now = Date.now();
                if (now - player.lastMoveTime < MOVE_MIN_INTERVAL_MS) return; // rate limit
                player.lastMoveTime = now;

                player.x = clampCoord(msg.x, player.x);
                player.y = clampCoord(msg.y, player.y);
                player.z = clampCoord(msg.z, player.z);
                if (Number.isFinite(Number(msg.yaw))) player.yaw = Number(msg.yaw);
                if (typeof msg.viewMode === 'string') player.viewMode = msg.viewMode.slice(0, 20);
                player.sprint = !!msg.sprint;

                broadcast({
                    type: 'playerMoved', connId,
                    x: player.x, y: player.y, z: player.z,
                    yaw: player.yaw, viewMode: player.viewMode, sprint: player.sprint,
                }, connId);
                break;
            }

            case 'nameChange': {
                if (!joined || !player) return;
                player.name = sanitizeName(msg.name);
                const profile = profiles.get(player.identityUuid);
                if (profile) profile.name = player.name;
                broadcast({ type: 'playerNameChanged', connId, name: player.name }, connId);
                break;
            }

            case 'skinChange': {
                if (!joined || !player) return;
                const skin = sanitizeSkin(msg.skin);
                if (!skin) return; // reject silently rather than propagate bad data
                player.skin = skin;
                const profile = profiles.get(player.identityUuid);
                if (profile) profile.skin = skin;
                broadcast({ type: 'playerSkinChanged', connId, skin: player.skin }, connId);
                break;
            }

            case 'chat': {
                if (!joined || !player) return;
                const now = Date.now();
                if (now - player.lastChatTime < CHAT_MIN_INTERVAL_MS) return; // spam guard
                player.lastChatTime = now;

                const text = sanitizeChatText(msg.text);
                if (!text) return;

                // Ephemeral by design: broadcast to everyone currently
                // connected (including the sender, for consistent ordering
                // in their own chat log) and never stored anywhere. New
                // joiners get no history at all.
                const chatMsg = { type: 'chat', connId, name: player.name, text };
                for (const p of players.values()) {
                    if (p.ws.readyState === p.ws.OPEN) p.ws.send(JSON.stringify(chatMsg));
                }
                break;
            }

            default:
                break; // unknown message type — ignore
        }
    });

    ws.on('close', () => {
        if (joined) {
            players.delete(connId);
            broadcast({ type: 'playerLeft', connId });
        }
    });
});

// Every 30s, ping everyone; anyone who didn't pong back since the last
// sweep gets terminated. terminate() fires the same 'close' handler above,
// so cleanup (removing from `players`, broadcasting playerLeft) happens
// the normal way — this just makes sure that actually happens for
// connections that died silently instead of closing cleanly.
const heartbeatInterval = setInterval(() => {
    wss.clients.forEach(ws => {
        if (ws.isAlive === false) return ws.terminate();
        ws.isAlive = false;
        ws.ping();
    });
}, 30000);
wss.on('close', () => clearInterval(heartbeatInterval));

server.listen(PORT, () => {
    console.log(`Hangout Area server running at http://localhost:${PORT}`);
    console.log(`WebSocket endpoint: ws://localhost:${PORT}/ws`);
    console.log(`Serving static files from: ${STATIC_DIR}`);
});
